version: '3'

services:
  cosmovisor:
    container_name: cosmovisor
    image: "octopus-appchains/otto"
    ports:
      - "26656-26657:26656-26657"
    command:
      - /bin/bash -c "/root/init_and_start.sh ottod cosmovisor otto_9900-1 29aa7bef50c930284202c89cfb9f4452e160bebb@35.234.3.39:26656,f33dfacf06344222bbd92b377de5d17e0c37ee02@104.199.233.115:26656 https://raw.githubusercontent.com/octopus-appchains/otto/feat/otto-upgrade-ccv/tests/genesis.json"